version: '3.4'

services:
  automationapi:
    image: ${DOCKER_REGISTRY-}automationapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ConnectionString=Server=db;Initial Catalog=otomation;User Id=sa;Password=Passw0rd.1

  db:
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: Passw0rd.1
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433 
    restart: always 